### PR TITLE
Symfony 3.0

### PR DESCRIPTION
**Pull request by smoench**

### CODE REVIEW

**Comment by DavidBadura** [comment]
:+1:

**Comment by tolry** [comment]
@smoench do we still need to keep our own fork or could we switch to the original?

**Comment by smoench** [comment]
@tolry depends on https://github.com/asm89/twig-lint/pull/30 :wink:

**Comment by DavidBadura** [comment]
this could take months :laughing:

**Comment by tolry** [comment]
@smoench great - let's merge this, until the master has caught up

**Pull request merged**
